### ISSUE TITLE
Cannot use setup-fortran in fpm CI for windows-latest + intel compiler

### ISSUE THREAD

**Issue by perazz** [awvwgk/setup-fortran#18]
See https://github.com/fortran-lang/fpm/actions/runs/4881173513/jobs/8709745595.

It looks like the shell returns `platform=mingw64_nt-10.0-20348` which is not supported by the `install_intel` script. 

I may be doing something wrong, but I don't see any changes in system shell or environment variables before the setup-fortran step. Thanks in advance for your help!

**Comment by perazz** [comment]
Uhm sorry, I just noticed #10, that support for Intel + Windows is still missing

**Comment by w-bonelli** [comment]
until supported here you might try https://github.com/modflowpy/install-intelfortran-action, which supports Windows, although there are some rough edges and un-cached install takes painfully long

**Comment by w-bonelli** [comment]
@perazz intel is now supported on windows
