### ISSUE TITLE
Support Intel compilers v.2023.2.0

### ISSUE THREAD

**Issue by amontoison** [awvwgk/setup-fortran#24]
Is it possible to support the latest release of the Intel compilers?
We use this great GitHub  actions in [GALAHAD](https://github.com/ralna/GALAHAD) for testing Fortran code with `ifort` and `ifx`.

cc: @jfowkes

**Comment by awvwgk** [comment]
The URL for MacOS is:

- https://registrationcenter-download.intel.com/akdlm/IRC_NAS/edb4dc2f-266f-47f2-8d56-21bc7764e119/m_HPCKit_p_2023.2.0.49443.dmg
