### ISSUE TITLE
cmake   No CMAKE_Fortran_COMPILER could be found.

### ISSUE THREAD

**Issue by afonari** [awvwgk/setup-fortran#6]
(Sorry for spamming with issues)

CMakeLists.txt header:
```
cmake_minimum_required(VERSION 2.6)
project(packmol Fortran)
```

Step example:
```
 - name: Compile using cmake
      if: matrix.compiler == 'cmake'
      run: |
        cmake ./ && cmake --build ./
      shell: bash
```

Error:
```
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_Fortran_COMPILER could be found.
```

See repo: https://github.com/afonari/packmol/

**Comment by afonari** [comment]
`project(XXX Fortran)` is a standard cmake directive

https://cmake.org/cmake/help/latest/command/project.html

Also people looking for solutions here for example: https://groups.google.com/g/comp.lang.fortran/c/Jna-QAHCOpk
and here: https://github.com/fortran-lang/stdlib/issues/328

**Comment by awvwgk** [comment]
I didn't found in the issue that you have a problem using this action on Windows. That you are using this action on a Windows runner for creating a CMake build would be the information I needed to help.

CMake compiler detection is another thing than being able to declare a Fortran project in CMake. The detection is platform specific and apparently different on Windows than on Unix platforms. Using `-DCMAKE_Fortran_COMPILER=$FC` seems like an easy to implement workaround in your pipeline to normalize the behavior for the different platforms.

**Comment by afonari** [comment]
> Using -DCMAKE_Fortran_COMPILER=$FC seems like an easy to implement workaround in your pipeline to normalize the behavior for the different platforms.

Yeah, this didn't work (also noted in the links I've posted). The solution is to install some Visual Studio intel component, I guess I will just drop windows from testing.

**Comment by w-bonelli** [comment]
@afonari might be worth trying a different CMake generator on Windows, e.g. `MinGW Makefiles`

see [here](https://github.com/modflowpy/install-intelfortran-action/issues/10)

**Comment by afonari** [comment]
@w-bonelli thanks for the pointer. Can you provide an example of compiling on windows using Cmake in the test file?
Somewhere around here maybe: https://github.com/modflowpy/install-intelfortran-action/blob/main/.github/workflows/ci.yml#L67

**Comment by w-bonelli** [comment]
@afonari see [this](https://github.com/modflowpy/install-intelfortran-action/issues/10#issuecomment-1309171273) comment, and passing Windows build [here](https://github.com/w-bonelli/MoorDyn/actions/runs/3430563754/jobs/5717687754#step:10:1)

Note, that build is not from a project I have any real familiarity with, and I'm pretty new to CMake &mdash; take with a grain of salt
